patch configure to link -lpthread on windows
conda-forge/r-ps-feedstock pull request #28
Opened 2024-10-12 09:26 UTC by brendanf

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2024-10-12 09:27 UTC, brendanf commented
@conda-forge-admin, please rerender

2024-10-12 09:27 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I was trying to look for recipes to lint for you, but it appears we have a merge conflict. Please try to merge or rebase with the base branch to resolve this conflict.

Please ping the 'conda-forge/core' team (using the @ notation in a comment) if you believe this is a bug.

2024-10-12 09:35 UTC, brendanf commented
@conda-forge-admin, please rerender

2024-10-12 11:08 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipe/meta.yaml```) and found some lint.

Here's what I've got...


For **recipe/meta.yaml**:

 * The source section contained an unexpected subsection name. patch is not a valid subsection name.

For **recipe/meta.yaml**:

 * Jinja2 variable references are suggested to take a ``{{<one space><variable name><one space>}}`` form. See lines [42].

2024-10-12 15:58 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe/meta.yaml```) and found it was in an excellent condition.
I do have some suggestions for making it better though...


For **recipe/meta.yaml**:

 * Jinja2 variable references are suggested to take a ``{{<one space><variable name><one space>}}`` form. See lines [43].

2024-10-12 17:15 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe/meta.yaml```) and found it was in an excellent condition.

2024-10-13 09:03 UTC, brendanf commented
I also opened a PR to patch this upstream https://github.com/r-lib/ps/pull/182

2024-10-13 09:07 UTC, brendanf commented
@conda-forge/r ready for review.  Changes welcome.

2024-10-13 09:07 UTC, brendanf commented
Fixes #27

2024-10-13 09:22 UTC, brendanf commented
@conda-forge-admin, please rerender

2024-10-14 08:54 UTC, mfansler requested changes
Thanks for working on this! ❤️ 

As long as the patch gets `-pthread` flag included during link, then the dependencies shouldn't need adjustment.

2024-10-14 08:54 UTC, mfansler commented on recipe/meta.yaml
> +    - mingw-w64-ucrt-x86_64-winpthreads-git  # [win]
Likely unnecessary - `libwinpthread` will automatically get pulled in and exported into run requirements. For example, see https://github.com/conda-forge/r-protolite-feedstock/pull/44.

```suggestion
```

2024-10-14 08:54 UTC, mfansler commented on recipe/meta.yaml
> +    - mingw-w64-ucrt-x86_64-winpthreads-git  # [win]
```suggestion
```

2024-10-14 11:11 UTC, brendanf commented
@mfansler You are right, that worked.

2024-10-14 12:47 UTC, mfansler approved these changes
Thanks again!

2024-10-14 12:47 UTC, merged